export default {
  auth: 'Авторизация',
  code_verification: 'Введите код',
  login_registration: 'Вход / регистрация',
  logout: 'Выйти',
  notifications: 'Уведомления',
  notification_settings: 'Настройки уведомлений',
  agreements: 'Юридическая информация',
  documents: 'Документы',
  chat_support: 'Чат с поддержкой',
  profile: 'Профиль',
  fill_profile: 'Заполните профиль',
  your_profile: 'Мой профиль',
  delete_profile: 'Удалить аккаунт',
  delete_profile_confirm: 'Вы уверены, что хотите удалить аккаунт?',
  recive_code: 'Получить код',
  settings: 'Настройки',
  sms_code: 'СМС код',
  themes_dark: 'Темная',
  themes_device: 'Тема устройства',
  themes_light: 'Светлая',
  currency: '%s %s',
  welcome: 'Добро пожаловать',
  good_morning: 'Доброе утро!',
  good_day: 'Добрый день!',
  good_evening: 'Добрый вечер!',
  good_night: 'Доброй ночи!',
  welcome_description: 'Выбирайте подходящие поездки',
  login: 'Вход',
  dont_have_account: 'У вас ещё нет аккаунта?',
  registration: 'Регистрация',
  forgot_password: 'Забыли пароль?',
  you_have_account: 'У вас уже есть аккаунт?',
  to_come_in: 'Войти или зарегистрироваться',
  email: 'Email',
  password: 'Пароль',
  step: 'Шаг %s из %s',
  phone_number: 'Номер телефона',
  сhoosing_way: 'Выберите способ подтверждения кода',
  country_code: 'Код страны',
  sent_code_you_phone: 'На ваш номер телефона\nвыслан код проверки',
  sent_code_your_phone: 'Код проверки был выслан на',
  sent_code_your_phone_telegram_google: 'Для подтверждения номера телефона введите код из Telegram, который вы получили.',
  sent_code_your_phone_sms_google: 'Для подтверждения номера телефона введите код из SMS, который вы получили.',
  sent_code_your_phone_telegram: 'Для подтверждения номера ',
  sent_code_your_phone_telegram_two: 'введите код из Telegram, который вы получили.',
  check_telegram: 'Нажмите сюда\nесли вас подтвердили в Телеграме',
  code_not_come: 'Отправить код повторно',
  what_is_you_name: 'Как вас зовут?',
  your_name: 'Ваше имя',
  name: 'Имя',
  your_surname: 'Ваша фамилия',
  surname: 'Фамилия',
  your_gender: 'Ваш пол',
  female: 'Женский',
  male: 'Мужской',
  birthday: 'Дата рождения',
  how_old_are_you: 'Дата рождения',
  dd: 'ДД',
  mm: 'ММ',
  hh: 'ЧЧ',
  yyyy: 'ГГГГ',
  id_confirmation: 'Подтверждение личности',
  you_ready_show_documents: 'Готовы ли вы показать документы водителю перед поездкой?',
  ready: 'Готов',
  not_ready: 'Не готов',
  ready_show_documents: 'Готов показать документы',
  dont_ready_show_documents: 'Не готов показать документы',
  pick_password: 'Придумайте пароль',
  input_password: 'Введите пароль',
  repeat_password: 'Повторите пароль',
  dowload_you_photo: 'Загрузите ваше фото',
  you_successfully: 'Вы успешно\nзарегистрировались!',
  pack_for_trip: 'Собирайте вещи в поездку',
  download_file: 'Загрузить файл',
  attachment_photo: 'Сделать фотографию',
  attachment_gallery: 'Выбрать из галереи',
  search_tour: 'Найти поездку',
  have_nice_ride: 'Счастливых поездок!',
  finish_registration: 'Завершить регистрацию',
  new_trip_depatrure: 'Откуда',
  new_trip_create: 'Создание поездки',
  new_trip_destination: 'Куда',
  new_trip_date: 'Дата поездки',
  new_trip_time: 'Во сколько состоится поездка?',
  new_trip_address_palceholder: 'Укажите адрес',
  new_trip_comment_placeholder: 'Выезжаю с московского, всем напишу предварительно.',
  full_name: 'ФИО',
  sex: 'Пол',
  telephone: 'Телефон',
  edit: 'Редактировать',
  edit_trip: 'Редактировать поездку',
  cancel_trip: 'Отменить поездку',
  finish_trip: 'Завершить поездку',
  change_password: 'Изменить пароль',
  edit_profile: 'Редактирование',
  user_contacts: 'Контакты',
  re_take: 'Переснять',
  next: 'Далее',
  save: 'Сохранить',
  cancel: 'Отменить',
  archive_trip: 'Архив поездок',
  inputPasswordDontMatch: 'Введенные пароли не совпадают',
  trip_search: 'Поиск поездки',
  date_trip: 'Дата поездки',
  search: 'Поиск',
  search_trip: 'Искать',
  where_you_to_go: 'Откуда вы хотите поехать?',
  where_to_you_finish: 'Куда вы хотите поехать?',
  input_info_location: 'Введите название улицы или здания',
  tripTime: 'В пути %s',
  hour: 'Часа',
  no_trip_this_day: 'Поездок не найдено',
  see_rides_another_day: 'Попробуйте позже, обычно поездки публикуются за 2-3 дня',
  next_day: 'Следущий день',
  main_page: 'На главную',
  price: 'Цена',
  time_in_trip: 'Время в пути:',
  driver_info: 'Информация о водителе',
  passengers: 'Пассажиры',
  passengers_description: 'Некоторые из пассажиров могут присоединяться в промежуточных пунктах.',
  book_now: 'Забронировать',
  no_more_place: 'Мест нет',
  verified_document: 'Подтвердить документы',
  no_other_passengers: 'Ещё нет других пассажиров',
  successfully_booked: 'Поездка забронирована!',
  have_a_nice_trip: 'Свяжитесь с водителем для\nобсуждения деталей поездки.',
  your_trip: 'Ваши поездки',
  create_trip: 'Создайте поездку, после ее публикации\nвы сможете найти ее тут',
  find_trip: 'Забронируйте поездку, после брони вы\nсможете найти ее тут',
  create_trip_botton: 'Создать поездку',
  published: 'Опубликованные',
  booked: 'Забронированные',
  quantity_passeners: 'Количество пассажиров:',
  bookeds: 'Забронировали:',
  hum: 'чел.',
  car: 'Автомобиль',
  add_car: 'Добавить автомобиль',
  add_car_process: 'Добавление автомобиля',
  edit_car_process: 'Редактирование',
  recovery_password: 'Восстановление пароля',
  by_number: 'По номеру',
  by_mail: 'По почте',
  input_mail: 'Введите email',
  input_telephone: 'Введите телефон',
  code_send_for_phone: 'На ваш номер телефона %s мы выслали код проверки',
  code_send_for_mail: 'На вашу почту %s мы выслали код проверки',
  repeat_request_code_telegram: 'Не подошел код?\nПроверьте номер телефона\nили отправьте код повторно',
  repeat_request_code: 'Код можно запросить через %s сек.',
  repeat_send_code: 'Код можно запросить повторно\nчерез %s сек.',
  you_successfully_changed_password: 'Вы успешно сменили пароль!',
  to_use_password_login: 'Теперь можете использовать его для входа в приложение',
  passengers_count: 'Сколько пассажиров возьмете?',
  seat_price: 'Какая будет цена за 1 место?',
  car_describe: 'Какой у вас автомобиль?',
  select_car: 'Выберите автомобиль',
  add_photo: 'Добавьте фото',
  add_passport: 'Добавить паспорт',
  take_selfie: 'Селфи с паспортом',
  take_selfie_detail: 'Постарайтесь сделать фотографию в светлом помещении, без солнечных очков и головного убора, чтобы ваше лицо было хорошо видно вместе с паспортом',
  take_photo_passport: 'Сфотографируйте паспорт для подтверждения личности',
  take_photo_passport_detail: 'Пожалуйста, сфотографируйте свой паспорт в двух разворотах: ФИО, текущая регистрация',
  take_photo_page_two:
    'Пожалуйста, убедитесь в том, что на фото четко видно ФИО, дату рождения, дату выдачи и кем выдан документ, а также серию и номер',
  check_photo_page_two:
    'Проверьте отчетливо ли видно запись о прописке, а также серию и номер паспорта',
  take_photo: 'Сделать фото',
  brand: 'Марка',
  model: 'Модель',
  color: 'Цвет',
  tell_about_trip: 'Расскажите подробнее о поездке',
  trip_bublished: 'Ваша поездка\nопубликована!',
  trip_bublished_description: 'Пассажиры забронируют место\nи поедут с вами',
  accept: 'Принять',
  today: 'сегодня',
  tomorrow: 'завтра',
  manufacture_year: 'Год выпуска',
  state_number: 'Госномер',
  yes: 'Да',
  yes_delete: 'Да, удалить',
  yes_logout: 'Да, выйти',
  delete_car_text: 'Вы уверены, что хотите удалить автомобиль?',
  look: 'Посмотреть',
  cancelled: 'Отменена',
  total_seats: 'Всего мест:',
  cost_of_travel: 'Стоимость поездки:',
  cost_of_travel_plan_text: 'Стоимость поездки',
  seats: {
    one: '{{count}} место',
    few: '{{count}} места',
    many: '{{count}} мест',
    other: '{{count}} мест',
  },
  seat: 'мест',
  one_seat: 'место',
  logout_confirm: 'Вы уверены, что хотите выйти из аккаунта?',
  push_notifications: 'Push-уведомления',
  mail_notifications: 'Почта',
  sms_notifications: 'SMS',
  continue: 'Продолжить',
  date_and_time: 'Дата и время',
  confirm: 'Подтвердить',
  confirm_cancel_trip: 'Вы уверены, что хотите отменить поездку?',
  confirm_finish_trip: 'Вы уверены, что хотите Завершить поездку?',
  confirm_cancel_booking: 'Вы уверены, что хотите отменить бронирование?',
  yes_cancel: 'Да, отменить',
  yes_finish: 'Да, завершить',
  dont_cancel: 'Не отменять',
  dont_finish: 'Не завершать',
  finished: 'Завершена',
  on_the_way: 'В пути',
  price_per_seat: 'Цена за место наличными:',
  trip_detail_screen_name: 'Детали поездки',
  comfort: 'Удобства',
  passenger_payment: 'Как пассажир будет оплачивать поездку?',
  passenger_payment_description: 'При оплате банковской картой деньги поступят на ваш счет после поездки.',
  cash: 'Наличными',
  card: 'Картой',
  confirm_booking_question: 'Хотите подтверждать бронирование?',
  confirm_booking_question_description: 'Пассажиры не смогут забронировать поездку без вашего одобрения.',
  confirm_yes: 'Хочу',
  confirm_no: 'Не хочу',
  trip_comment: 'Оставьте комментарий к вашей поездке',
  trip_comment_short: 'Комментарий к поездке',
  has_baby_chair: 'Есть детское кресло',
  ready_take_delivery: 'Готовы взять посылку',
  max_2_behind: 'Максимум двое сзади',
  allow_animals: 'Можно с животными',
  allow_smoke: 'Можно курить',
  allow_cargo: 'Можно с грузом',
  disallow_animals: 'Нельзя с животными',
  disallow_cargo: 'Нельзя с грузом',
  disallow_smoke: 'Нельзя курить',
  add_intermediate_cities: 'Добавьте\nпромежуточные пункты',
  intermediate_cities_description: 'Таким образом больше попутчиков сможет присоединиться к поездке',
  we_recommend: 'Мы рекомендуем:',
  add_intermediate: 'Добавить пункт',
  adding_intermediate: 'Добавление пункта',
  skip: 'Пропустить',
  trip_price: 'Рекомендуемая стоимость поездки',
  publish_trip: 'Опубликовать поездку',
  to_main: 'На главную',
  filtering: 'Фильтрация',
  trip_filter_order: 'Показывать сначала',
  trip_filter_earlier: 'Самые ранние поездки',
  trip_filter_cheaper: 'Самые дешевые поездки',
  trip_filter_nearest_departure: 'Самые близкие к месту отправления',
  trip_filter_nearest_destination: 'Самые близкие к месту прибытия',
  trip_filter_depatrure_time: 'Время выезда',
  reset_all: 'Сбросить все',
  watch: 'Смотреть',
  aboutTrip: 'Подробнее о поездке',
  driver: 'Водитель',
  write: 'Написать',
  call: 'Позвонить',
  trip_actions: 'Действия',
  cancel_booking: 'Отменить бронирование',
  trip_wo_passengers: 'Поездку еще никто не забронировал',
  change_route: 'Изменить маршрут',
  change_time: 'Изменить дату и время',
  route: 'Маршрут',
  hide_intermediate_cities: 'Скрыть промежуточные пункты',
  show_intermediate_cities: 'Показать промежуточные пункты',
  car_required: 'Необходимо выбрать автомобиль',
  user: 'Пользователь',
  age: {
    one: '{{count}} год',
    few: '{{count}} года',
    many: '{{count}} лет',
    other: '{{count}} лет',
  },
  rides: {
    one: '{{count}} поездка',
    few: '{{count}} поездки',
    many: '{{count}} поездок',
    other: '{{count}} поездок',
  },
  registered_less_months: 'Зарегистрирован менее {{count}} месяцa назад',
  registered_more_months: {
    one: 'Зарегистрирован более {{count}} месяца назад',
    few: 'Зарегистрирован более {{count}} месяцев назад',
    many: 'Зарегистрирован более {{count}} месяцев назад',
    other: 'Зарегистрирован более {{count}} месяцев назад',
  },
  registered_more_years: {
    one: 'Зарегистрирован более {{count}} года назад',
    few: 'Зарегистрирован более {{count}} лет назад',
    many: 'Зарегистрирован более {{count}} лет назад',
    other: 'Зарегистрирован более {{count}} лет назад',
  },
  year: 'год',
  additionally: 'Дополнительно',
  registry: 'Зарегестрирован',
  back: 'назад',
  months: 'месяца',
  one_years: 'года',
  three_years: 'трёх лет',
  ten_years: 'десяти лет',
  phone_confirm: 'Номер подтвержден',
  show_docs_ready: 'Могу документы перед поездкой',
  less: 'менее',
  more: 'более',
  max_intermediate: 'Можно добавить максимум %s точек',
  not_required: '(необязательно)',
  required: 'Обязательное поле',
  code_error: 'Неверно введен код. Попробуйте еще раз',
  booking_trip: 'Бронирование поездки',
  booking_seats: 'Сколько мест хотите забронировать?',
  any_time: 'Любое',
  CLIENT_ERROR: 'Неизвестная ошибка приложения',
  SERVER_ERROR: 'Неизвестная ошибка сервера',
  TIMEOUT_ERROR: 'Время ожидания ответа от сервера истекло',
  CONNECTION_ERROR: 'Сервер недоступен',
  NETWORK_ERROR: 'Hет подключения к интернету',
  UNKNOWN_ERROR: 'Неизвестная ошибка',
  auth_agreement:
    'Принимаю условия [политики конфиденциальности](privacy_policy) и [обработки персональных данных](personal_data)',
}
